id: AE76DA47A
title: Brief Protectors Practice
type: translation
pechas:
- I622AF2A8
- ID1DDF9AD
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:52:10.350395
  last_modified_at: 2023-01-04 11:52:10.350421
  collections:
  - Fifth Dzogchen Rinpoche
  - Works of Tibetan Masters
alignment_to_base:
  I622AF2A8/7B81: C952
  ID1DDF9AD/4073: C952
